app = "part3-notes-backend-part4-8"
primary_region = "sfo"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_001
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
