
name: Periodic Health Check

on:
  push:
    branches:
      - main  # Triggered on push to main branch
  schedule:
    - cron: '0 0 * * *'  # Scheduled trigger to run every day at midnight UTC

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ping deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          # The URLs you want to health check
          url: https://your-deployed-service.com
          # Whether to follow redirects (optional)
          follow-redirect: false
          # Maximum retry attempts
          max-attempts: 3
          # Delay between retries
          retry-delay: 5s
          # Retry all errors, including 404
          retry-all: false
          # Optional cookie for the request
          cookie: "token=your-token"
          # Optional Basic Authentication
          basic-auth: "your-username:your-password"

