steps:
  - name: Deploy to production
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    run: |
      echo "Deploying application..."
      # Add your deployment commands here
