name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu environment
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set the Node.js version to use (this matches your requirement)
    
    - name: Install dependencies
      run: npm install  # Install the necessary dependencies
    
    - name: Build the production version
      run: npm run build  # Build the project (this assumes the build script is configured in package.json)
    
    - name: Install Flyctl
      run: |
        curl -L https://fly.io/install.sh | sh  # Install the Fly.io CLI
        
    

   
