name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Frontend - Install and Test
        working-directory: ./frontend
        run: |
          npm install
          npm test

      - name: Backend - Install and Test
        working-directory: ./
        run: |
          npm install
          npm test

  deploy:
    needs: test_and_lint
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: echo "Deployment Step (add your script)"
