name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Application
        run: |
          npm run build

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Add your deployment commands here
